# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-07 07:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='day',
            field=models.CharField(choices=[('Su', 'Sunday'), ('Mo', 'Modnday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Te', 'Thursday')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='pickFrom',
            field=models.CharField(default=datetime.datetime(2017, 11, 7, 7, 47, 51, 512280, tzinfo=utc), max_length=200),
        ),
        migrations.AddField(
            model_name='leave',
            name='pickTo',
            field=models.CharField(default=datetime.datetime(2017, 11, 7, 7, 47, 51, 512336, tzinfo=utc), max_length=200),
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('AP', 'Approve'), ('DA', 'Disapprove'), ('PE', 'Pending')], default='PE', max_length=2),
        ),
    ]
