# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-08 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_auto_20171107_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.CharField(default=datetime.datetime(2017, 11, 8, 15, 5, 4, 534222, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.CharField(default=datetime.datetime(2017, 11, 8, 15, 5, 4, 534259, tzinfo=utc), max_length=200),
        ),
    ]
