# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_auto_20171108_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 14, 34, 33, 295225, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.CharField(default=datetime.datetime(2017, 11, 12, 14, 34, 33, 295272, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('SL', 'Sick Leave'), ('TL', 'Temporary Leave'), ('PL', 'Personal Leave'), ('AW', 'Adverse Weather'), ('ML', 'Maternity leave')], max_length=2),
        ),
    ]
