# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-13 10:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_auto_20171113_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.CharField(default=datetime.datetime(2017, 11, 13, 10, 30, 6, 631454, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.CharField(default=datetime.datetime(2017, 11, 13, 10, 30, 6, 631496, tzinfo=utc), max_length=200),
        ),
    ]
