# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-22 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0008_auto_20171122_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.DateField(default=datetime.datetime(2017, 11, 22, 14, 44, 32, 439609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.DateField(default=datetime.datetime(2017, 11, 22, 14, 44, 32, 439648, tzinfo=utc)),
        ),
    ]
