# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-22 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0009_auto_20171122_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 15, 37, 1, 836839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 15, 37, 1, 836877, tzinfo=utc)),
        ),
    ]
