# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-26 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0010_auto_20171122_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 26, 15, 37, 33, 400383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 26, 15, 37, 33, 400430, tzinfo=utc)),
        ),
    ]
