# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-29 11:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0011_auto_20171126_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 29, 11, 12, 5, 706628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 29, 11, 12, 5, 706664, tzinfo=utc)),
        ),
    ]
