# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-03 07:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0015_auto_20171203_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 7, 59, 53, 304207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 7, 59, 53, 304248, tzinfo=utc)),
        ),
    ]
