# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-03 09:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0016_auto_20171203_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='pickFrom',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 9, 35, 17, 669509, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='leave',
            name='pickTo',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 9, 35, 17, 669556, tzinfo=utc)),
        ),
    ]
