# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-29 11:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0004_auto_20171126_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='performance',
            name='year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 29, 11, 12, 5, 717628, tzinfo=utc), null=True),
        ),
    ]
