# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-29 12:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20171129_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 29, 12, 41, 3, 606348, tzinfo=utc), null=True),
        ),
    ]
