# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-29 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20171129_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 11, 29, 13, 5, 15, 941348, tzinfo=utc), null=True),
        ),
    ]
