# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-03 07:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0007_auto_20171129_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_team',
        ),
        migrations.AlterField(
            model_name='performance',
            name='year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 12, 3, 7, 58, 36, 777999, tzinfo=utc), null=True),
        ),
    ]
