# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_auto_20171203_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_sprint', models.DateField(blank=True)),
                ('end_sprint', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PL', 'Planning'), ('WO', 'Working'), ('QA', 'QA'), ('DE', 'Deploy'), ('RV', 'Review'), ('RE', 'Retro'), ('CL', 'Closed')], default='PE', max_length=2)),
                ('sprint_length', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='end_project',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='project_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='start_project',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('PL', 'Planning'), ('SP', 'Sprint'), ('RE', 'Release'), ('UA', 'UAT'), ('HO', 'Handover'), ('CL', 'Closed')], default='PL', max_length=2),
        ),
        migrations.RemoveField(
            model_name='performance',
            name='month',
        ),
        migrations.AddField(
            model_name='performance',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='performance',
            name='year',
        ),
        migrations.AddField(
            model_name='performance',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Team'),
        ),
    ]
