# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-06 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0011_auto_20171206_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project_length',
            field=models.IntegerField(null=True),
        ),
    ]
