# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-06 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0012_team_project_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project_budget',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_cost_per_hour',
            field=models.FloatField(null=True),
        ),
    ]
