# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='started_at',
            field=models.DateTimeField(),
        ),
    ]
