# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_token', models.CharField(max_length=255)),
                ('toggl_token', models.CharField(max_length=255)),
            ],
        ),
    ]
