# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-13 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auto_20161213_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WA', 'Waiting'), ('WO', 'working'), ('CO', 'Completed')], default='WI', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
