# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-18 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
